import mongoose from "mongoose";

const Schema = mongoose.Schema;

const userSchema = new Schema({
    user_id: String,
    user_account_id: String,
    bse_user_id: String,
    bse_mandate_id: String,
    fno_status: String,
    first_name: String,
    last_name: String,
    email_id: String,
    mobile_number: String,
    country_code: String,
    enabled: Boolean,
    bse_enabled: Boolean,
    mandate_id_linked: Boolean,
    bse_fatca: Boolean,
    email_verified: Boolean,
    has_invitation: Boolean,
    mobile_verified: Boolean,
    aof_enabled: Boolean,
    gmail_user: Boolean,
    connection_imported: Boolean,
    aof_status: String,
    kyc_status: String,
    kyc_details: String,
    onboarding_status: String,
    investment_status: String,
    investment_event_sent: Boolean,
    image_url: String,
    search_id: String,
    description: String,
    author_is_user: Boolean,
    is_kyc_verified: Boolean,
    is_expert: Boolean,
    is_direct_plan: Boolean,
    is_suspended: Boolean,
    blocked_accounts_info: {
        wallet: Boolean,
        mutualFund: Boolean,
        stocks: Boolean,
    },
    user_role: Array,
    tags: Array,
    created_at: String,
    kyc_mode: String,
    utm_source: String,
    utm_medium: String,
    utm_campaign: String,
    utm_ref_code: String,
    super_user_account_id: String,
    is_child_user: Boolean,
    google_account: String,
    stocks_status: String,
    is_stocks_invited: Boolean,
    groww_kyc_status: String,
    demat_account_status: String,
});

export default mongoose.model("user", userSchema, "users");
