import mongoose from "mongoose";

const Schema = mongoose.Schema;

const userSchema = new Schema({
    user_id: { type: String, default: null },
    user_account_id: { type: String, default: "" },
    bse_user_id: { type: String, default: "" },
    bse_mandate_id: { type: String, default: null },
    fno_status: { type: String, default: "NOT_COMPLETED" },
    first_name: { type: String, default: "" },
    last_name: { type: String, default: null },
    email_id: { type: String, default: "" },
    mobile_number: { type: String, default: "" },
    country_code: { type: String, default: "" },
    enabled: { type: Boolean, default: true },
    bse_enabled: { type: Boolean, default: false },
    mandate_id_linked: { type: Boolean, default: false },
    bse_fatca: { type: Boolean, default: false },
    email_verified: { type: Boolean, default: true },
    has_invitation: { type: Boolean, default: false },
    mobile_verified: { type: Boolean, default: true },
    aof_enabled: { type: Boolean, default: false },
    gmail_user: { type: Boolean, default: true },
    connection_imported: { type: Boolean, default: false },
    aof_status: { type: String, default: "NOT_CREATED" },
    kyc_status: { type: String, default: "NA" },
    kyc_details: { type: String, default: "NA" },
    onboarding_status: { type: String, default: "NA" },
    investment_status: { type: String, default: "NOT_INVESTED" },
    investment_event_sent: { type: Boolean, default: false },
    image_url: {
        type: String,
        default:
            "https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png",
    },
    search_id: { type: String, default: "" },
    description: { type: String, default: "" },
    author_is_user: { type: String, default: "" },
    is_kyc_verified: { type: Boolean, default: true },
    is_expert: { type: Boolean, default: false },
    is_direct_plan: { type: Boolean, default: true },
    is_suspended: { type: Boolean, default: false },
    blocked_accounts_info: {
        wallet: { type: Boolean, default: false },
        mutualFund: { type: Boolean, default: false },
        stocks: { type: Boolean, default: false },
    },
    user_role: Array,
    tags: Array,
    created_at: { type: Date, default: Date.now },
    kyc_mode: { type: String, default: "NA" },
    utm_source: { type: String, default: "app" },
    utm_medium: { type: String, default: "app" },
    utm_campaign: { type: String, default: "app" },
    utm_ref_code: { type: String, default: null },
    super_user_account_id: { type: String, default: "" },
    is_child_user: { type: Boolean, default: false },
    google_account: { type: String, default: null },
    stocks_status: { type: String, default: "NOT_COOMPLETED" },
    is_stocks_invited: { type: Boolean, default: true },
    groww_kyc_status: { type: String, default: "NA" },
    demat_account_status: { type: String, default: "PENDING" },
});

export default mongoose.model("user", userSchema, "users");
